routes/web.php
<?php

//all pages routes
Route::get('/', 'PagesController@index')->name('pages.index');
Route::get('/galleries', 'PagesController@galleries')->name('pages.galleries');
Route::get('/contact', 'PagesController@contact')->name('pages.contact');
Route::get('/about', 'PagesController@about')->name('pages.about');
Route::get('/publications', 'PagesController@publications')->name('pages.publications');
Route::get('/events', 'PagesController@event')->name('pages.events');
Route::get('/event-details/{event}', 'PagesController@eventDetails')->name('pages.event-details');
Route::get('/events/{event}/register', 'PagesController@event_register_create')->name('pages.event_register.create');
Route::post('/events/register', 'PagesController@event_register_store')->name('pages.event_register.store');
Route::get('/training_mentorship', 'PagesController@training_mentorship')->name('pages.training_mentorship');
Route::get('/training_mentorship_single/{programme}', 'PagesController@training_mentorship_single')->name('pages.training_mentorship_single');
Route::get('/sponsors', 'PagesController@sponsors')->name('pages.sponsors');
Route::get('/search', 'PagesController@search')->name('pages.search');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');


// starting of dashboard routes
Route::prefix('dashboard')->group(function () {

    //allow this page to be accessed by admin and auth users only
    Route::resource('/registration_code', 'RegistrationCodeController')->middleware('auth','admin');

    //administrator routes only
    Route::middleware(['web','admin'])->group(function () {
        Route::get('/', 'DashboardController@index')->name('dashboard.index');
        Route::resource('/event', 'EventController');
        Route::resource('/gallery', 'GalleryController');
        Route::resource('/title', 'TitleController');
        Route::resource('/assoc_school', 'AssocSchoolController');
        Route::resource('/sponsor', 'SponsorController');
        Route::resource('/publication', 'PublicationController');
        Route::resource('/publicationCategory', 'PublicationCategoryController');
        Route::resource('/slider', 'SliderController');
        Route::resource('/training_mentorship', 'TrainingMentorshipController');
        Route::resource('/constitution', 'ConstitutionController');
        Route::resource('/mission', 'MissionController');
        Route::resource('/contact', 'ContactController');
        Route::resource('/newsponsor', 'NewSponsorController')->except('create');
        Route::resource('/abstractresearch', 'AbstractResearchController');
        Route::resource('/account', 'AccountController');


    });
});

// end of dasboard routes

app/NewSponsor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NewSponsor extends Model
{
    //
}

app/Http/Controllers/NewSponsorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\NewSponsor;
Use Session;
class NewSponsorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    // public function __construct()
    // {
    //     $this->middleware(['admin']);
        
    // }
    
    public function index()
    {
        $new = NewSponsor::all();
        return view('newSponsor.index')->withNew($new);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $this->validate($request, array(
            'fullname'      => 'string|required',
            'company'       => 'string|required',
            'email'         => 'email|required',
            'telephone'     => 'numeric|required|min:10',
            'message'       => 'required|string',
           
        ));
        

        $newSponsor = new NewSponsor;

        $newSponsor->fullname       = $request->fullname;
        $newSponsor->company        = $request->company;
        $newSponsor->email          = $request->email;
        $newSponsor->telephone      = $request->telephone;
        $newSponsor->message        = $request->message;
        $newSponsor->save();
        
        
        Session::flash('success', 'Thank You. Wel Will Contact You Shortly');
        return redirect()->route('pages.sponsors');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $new  = NewSponsor::find($id);
        return view('newsponsor.show')->withNew($new);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $new  = NewSponsor::find($id);
        $new->delete();
        Session::flash('success','Deleted Successfully');
        return redirect()->route('newsponsor.index');
    }
}

resources/views/newSponsor/index.blade.php
@extends('Layouts.dashboard')
@section('title', '| Sponsors')

@section('content')
<div class="col-lg-12">
    <!-- USER DATA-->
    @include('partials._message')

    <div class="user-data m-b-30">
        <h3 class="title-3 m-b-30">
            <i class="zmdi zmdi-account-calendar">New Sponsor Request</i>
        </h3>


        <div class="table-responsive table-data">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            <label class="au-checkbox">
                                <input type="checkbox">
                                <span class="au-checkmark"></span>
                            </label>
                        </td>

                        <td><b>Company Name</b></td>
                        <td><b>Full Name</b></td>
                        <td><b>Email</b></td>
                        <td><b>Contact</b></td>
                        <td><b>Message</b></td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($new as $sponsor)
                    <tr>
                        <td>
                            <label class="au-checkbox">
                                <input type="checkbox">
                                <span class="au-checkmark"></span>
                            </label>
                        </td>
                        <td>
                            <div class="table-data__info">
                                <h6>{{$sponsor->company}}</h6>
                            </div>
                        </td>
                        <td>
                            <div class="table-data__info">
                                <h6>{{$sponsor->fullname}}</h6>
                            </div>
                        </td>
                        <td>
                            <div class="table-data__info">
                                <h6>{{$sponsor->email}}</h6>
                            </div>
                        </td>
                        <td>
                            <div class="table-data__info">
                                <h6>{{$sponsor->telephone}}</h6>
                            </div>
                        </td>

                        <td>
                            <div class="table-data__info">
                                <h6>{{ substr($sponsor->message, 0, 100)}}{{ strlen($sponsor->message )> 100 ?"...":"" }}
                                </h6>
                            </div>
                        </td>
                        <td>
                            <div class="table-data-feature">
                                <a href="{{route('newsponsor.show', $sponsor->id)}}"><button class="item" type="submit"
                                        data-toggle="tooltip" data-placement="top" title="view">
                                        <i class="zmdi zmdi-eye" style="color:blue"></i>
                                    </button><a>

                                        {{Form::Open(['route'=>['newsponsor.destroy',$sponsor->id], 'method'=>'delete'])}}
                                        <button class="item" type="submit" data-toggle="tooltip" data-placement="top"
                                            title="Delete">
                                            <i class="zmdi zmdi-delete" style="color:red"></i>
                                        </button>
                                        {{Form::close()}}
                            </div>
                        </td>
                    </tr>
                    @empty
                    @endforelse


                </tbody>
            </table>
        </div>

    </div>
    <!-- END USER DATA-->
</div>

@endsection

resources/views/newSponsor/show.blade.php
@extends('Layouts.dashboard')
@section('title', '| Event-Details')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">Add New Event</div>
            <div class="card-body">
                <div class="card-title">
                    <h3 class="text-center title-2">New Event</h3>
                </div>
                <hr>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">Event</div>
                            <div class="card-body">
                                <div class="card-title">
                                    <h3 class="text-center title-2"> Event</h3>
                                </div>
                                <hr>

                                {{ Form::model($new) }}
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            {{ Form::label('name', 'Full Name', ['class' => 'control-label mb-1']) }}
                                            {{ Form::text('fullname', null, ['class' => 'form-control', 'disabled'=>'true'])}}
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            {{ Form::label('Company', 'Company', ['class' => 'control-label mb-1']) }}
                                            {{ Form::text('company', null, ['class' => 'form-control', 'disabled'=>'true'])}}
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            {{ Form::label('email', 'email', ['class' => 'control-label mb-1']) }}
                                            {{ Form::text('email', null, ['class' => 'form-control', 'disabled'=>'true'])}}
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            {{ Form::label('contact', 'contact', ['class' => 'control-label mb-1']) }}
                                            {{ Form::text('telephone', null, ['class' => 'form-control', 'disabled'=>'true'])}}
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <div class="form-group">
                                            {{ Form::label('content', 'Event Content', ['class' => 'control-label mb-1']) }}
                                            {{ Form::textarea('message', null, ['class' => 'form-control', 'disabled'=>'true'])}}
                                        </div>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <a href="{{route('sponsor.index')}}" class="btn btn-success btn-block">Ok</a>
                                    </div>
                                </div>
                                {{Form::close()}}
                            </div>
                        </div>
                    </div>

                </div>



                @endsection